<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <RuntimeIdentifiers>win-x64;linux-x64;linux-arm64</RuntimeIdentifiers>
    </PropertyGroup>

    <ItemGroup>
        <Folder Include="Assets\" />
        <Folder Include="Models\"/>
        <AvaloniaResource Include="Assets\**"/>
        <Folder Include="ViewModels\" />
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="obj_temp\**\*.cs" />
        <Compile Remove="bin_temp\**\*.cs" />
        <EmbeddedResource Remove="obj_temp\**\*" />
        <EmbeddedResource Remove="bin_temp\**\*" />
        <None Remove="obj_temp\**\*" />
        <None Remove="bin_temp\**\*" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.3.12"/>
        <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.3.12" />
        <PackageReference Include="Avalonia.Desktop" Version="11.3.12"/>
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.12"/>
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.12"/>
        <PackageReference Include="NAudio" Version="2.2.1" />
        <PackageReference Include="LibVLCSharp" Version="3.8.5" />
        <PackageReference Include="TagLibSharp" Version="2.3.0" />
        <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.21"
                          Condition="$([MSBuild]::IsOSPlatform('Windows')) Or '$(RuntimeIdentifier)' == 'win-x64' Or '$(RuntimeIdentifier)' == 'win-x86' Or '$(RuntimeIdentifier)' == 'win-arm64'" />
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Include="Avalonia.Diagnostics" Version="11.3.12">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
    </ItemGroup>
</Project>
